const staticServices = [
          { id: 1000, category_id: 1, name: 'Tap Repair', description: 'Professional tap repair service by expert technicians.', price: 299, duration_minutes: 30 },
          { id: 1001, category_id: 1, name: 'Pipe Leakage', description: 'Professional pipe leakage service by expert technicians.', price: 349, duration_minutes: 45 },
          { id: 1002, category_id: 1, name: 'Drain Cleaning', description: 'Professional drain cleaning service by expert technicians.', price: 399, duration_minutes: 60 },
          { id: 1003, category_id: 1, name: 'Sink Repair', description: 'Professional sink repair service by expert technicians.', price: 449, duration_minutes: 75 },
          { id: 1004, category_id: 1, name: 'Toilet Repair', description: 'Professional toilet repair service by expert technicians.', price: 499, duration_minutes: 90 },
          { id: 1005, category_id: 1, name: 'Water Tank Repair', description: 'Professional water tank repair service by expert technicians.', price: 549, duration_minutes: 105 },
          { id: 1006, category_id: 1, name: 'Bathroom Plumbing', description: 'Professional bathroom plumbing service by expert technicians.', price: 599, duration_minutes: 120 },
          { id: 1007, category_id: 2, name: 'Switch & Socket Repair', description: 'Professional switch & socket repair service by expert technicians.', price: 199, duration_minutes: 30 },
          { id: 1008, category_id: 2, name: 'Fan Installation', description: 'Professional fan installation service by expert technicians.', price: 249, duration_minutes: 45 },
          { id: 1009, category_id: 2, name: 'Light Installation', description: 'Professional light installation service by expert technicians.', price: 299, duration_minutes: 60 },
          { id: 1010, category_id: 2, name: 'Wiring Repair', description: 'Professional wiring repair service by expert technicians.', price: 349, duration_minutes: 75 },
          { id: 1011, category_id: 2, name: 'MCB Repair', description: 'Professional mcb repair service by expert technicians.', price: 399, duration_minutes: 90 },
          { id: 1012, category_id: 2, name: 'Short-Circuit Repair', description: 'Professional short-circuit repair service by expert technicians.', price: 449, duration_minutes: 105 },
          { id: 1013, category_id: 2, name: 'Inverter Installation', description: 'Professional inverter installation service by expert technicians.', price: 499, duration_minutes: 120 },
          { id: 1014, category_id: 3, name: 'AC Service', description: 'Professional ac service service by expert technicians.', price: 499, duration_minutes: 60 },
          { id: 1015, category_id: 3, name: 'AC Repair', description: 'Professional ac repair service by expert technicians.', price: 549, duration_minutes: 75 },
          { id: 1016, category_id: 3, name: 'AC Installation', description: 'Professional ac installation service by expert technicians.', price: 599, duration_minutes: 90 },
          { id: 1017, category_id: 3, name: 'AC Gas Refill', description: 'Professional ac gas refill service by expert technicians.', price: 649, duration_minutes: 105 },
          { id: 1018, category_id: 3, name: 'AC Cleaning', description: 'Professional ac cleaning service by expert technicians.', price: 699, duration_minutes: 120 },
          { id: 1019, category_id: 3, name: 'Cooler Repair', description: 'Professional cooler repair service by expert technicians.', price: 749, duration_minutes: 135 },
          { id: 1020, category_id: 4, name: 'Refrigerator Repair', description: 'Professional refrigerator repair service by expert technicians.', price: 349, duration_minutes: 45 },
          { id: 1021, category_id: 4, name: 'Washing Machine Repair', description: 'Professional washing machine repair service by expert technicians.', price: 399, duration_minutes: 60 },
          { id: 1022, category_id: 4, name: 'Microwave Repair', description: 'Professional microwave repair service by expert technicians.', price: 449, duration_minutes: 75 },
          { id: 1023, category_id: 4, name: 'Geyser Repair', description: 'Professional geyser repair service by expert technicians.', price: 499, duration_minutes: 90 },
          { id: 1024, category_id: 4, name: 'Water Purifier Service', description: 'Professional water purifier service service by expert technicians.', price: 549, duration_minutes: 105 },
          { id: 1025, category_id: 5, name: 'Furniture Repair', description: 'Professional furniture repair service by expert technicians.', price: 249, duration_minutes: 60 },
          { id: 1026, category_id: 5, name: 'Door Repair', description: 'Professional door repair service by expert technicians.', price: 299, duration_minutes: 75 },
          { id: 1027, category_id: 5, name: 'Lock Installation', description: 'Professional lock installation service by expert technicians.', price: 349, duration_minutes: 90 },
          { id: 1028, category_id: 5, name: 'Cabinet Repair', description: 'Professional cabinet repair service by expert technicians.', price: 399, duration_minutes: 105 },
          { id: 1029, category_id: 5, name: 'Shelf Installation', description: 'Professional shelf installation service by expert technicians.', price: 449, duration_minutes: 120 },
          { id: 1030, category_id: 5, name: 'Bed Repair', description: 'Professional bed repair service by expert technicians.', price: 499, duration_minutes: 135 },
          { id: 1031, category_id: 6, name: 'Full Home Cleaning', description: 'Professional full home cleaning service by expert technicians.', price: 999, duration_minutes: 120 },
          { id: 1032, category_id: 6, name: 'Kitchen Cleaning', description: 'Professional kitchen cleaning service by expert technicians.', price: 1049, duration_minutes: 135 },
          { id: 1033, category_id: 6, name: 'Bathroom Cleaning', description: 'Professional bathroom cleaning service by expert technicians.', price: 1099, duration_minutes: 150 },
          { id: 1034, category_id: 6, name: 'Sofa Cleaning', description: 'Professional sofa cleaning service by expert technicians.', price: 1149, duration_minutes: 165 },
          { id: 1035, category_id: 6, name: 'Carpet Cleaning', description: 'Professional carpet cleaning service by expert technicians.', price: 1199, duration_minutes: 180 },
          { id: 1036, category_id: 6, name: 'Floor Cleaning', description: 'Professional floor cleaning service by expert technicians.', price: 1249, duration_minutes: 195 },
          { id: 1037, category_id: 7, name: 'Room Painting', description: 'Professional room painting service by expert technicians.', price: 1499, duration_minutes: 240 },
          { id: 1038, category_id: 7, name: 'Full Home Painting', description: 'Professional full home painting service by expert technicians.', price: 1549, duration_minutes: 255 },
          { id: 1039, category_id: 7, name: 'Wall Touch-up', description: 'Professional wall touch-up service by expert technicians.', price: 1599, duration_minutes: 270 },
          { id: 1040, category_id: 7, name: 'Exterior Painting', description: 'Professional exterior painting service by expert technicians.', price: 1649, duration_minutes: 285 },
          { id: 1041, category_id: 7, name: 'Waterproof Painting', description: 'Professional waterproof painting service by expert technicians.', price: 1699, duration_minutes: 300 },
          { id: 1042, category_id: 8, name: 'Bathroom Deep Cleaning', description: 'Professional bathroom deep cleaning service by expert technicians.', price: 399, duration_minutes: 60 },
          { id: 1043, category_id: 8, name: 'Shower Repair', description: 'Professional shower repair service by expert technicians.', price: 449, duration_minutes: 75 },
          { id: 1044, category_id: 8, name: 'Toilet Repair', description: 'Professional toilet repair service by expert technicians.', price: 499, duration_minutes: 90 },
          { id: 1045, category_id: 8, name: 'Basin Repair', description: 'Professional basin repair service by expert technicians.', price: 549, duration_minutes: 105 },
          { id: 1046, category_id: 8, name: 'Exhaust Fan Installation', description: 'Professional exhaust fan installation service by expert technicians.', price: 599, duration_minutes: 120 },
          { id: 1047, category_id: 9, name: 'General Inspection', description: 'Professional general inspection service by expert technicians.', price: 499, duration_minutes: 90 },
          { id: 1048, category_id: 9, name: 'Minor Repairs', description: 'Professional minor repairs service by expert technicians.', price: 549, duration_minutes: 105 },
          { id: 1049, category_id: 9, name: 'Wall Repair', description: 'Professional wall repair service by expert technicians.', price: 599, duration_minutes: 120 },
          { id: 1050, category_id: 9, name: 'Grouting', description: 'Professional grouting service by expert technicians.', price: 649, duration_minutes: 135 },
          { id: 1051, category_id: 9, name: 'Waterproofing', description: 'Professional waterproofing service by expert technicians.', price: 699, duration_minutes: 150 },
          { id: 1052, category_id: 9, name: 'Home Inspection', description: 'Professional home inspection service by expert technicians.', price: 749, duration_minutes: 165 },
          { id: 1053, category_id: 10, name: 'CCTV Installation', description: 'Professional cctv installation service by expert technicians.', price: 599, duration_minutes: 90 },
          { id: 1054, category_id: 10, name: 'Smart Lock Installation', description: 'Professional smart lock installation service by expert technicians.', price: 649, duration_minutes: 105 },
          { id: 1055, category_id: 10, name: 'Doorbell Installation', description: 'Professional doorbell installation service by expert technicians.', price: 699, duration_minutes: 120 },
          { id: 1056, category_id: 10, name: 'Wi-Fi Camera Setup', description: 'Professional wi-fi camera setup service by expert technicians.', price: 749, duration_minutes: 135 },
          { id: 1057, category_id: 11, name: 'Garden Maintenance', description: 'Professional garden maintenance service by expert technicians.', price: 349, duration_minutes: 60 },
          { id: 1058, category_id: 11, name: 'Lawn Cleaning', description: 'Professional lawn cleaning service by expert technicians.', price: 399, duration_minutes: 75 },
          { id: 1059, category_id: 11, name: 'Plant Maintenance', description: 'Professional plant maintenance service by expert technicians.', price: 449, duration_minutes: 90 },
          { id: 1060, category_id: 11, name: 'Balcony Cleaning', description: 'Professional balcony cleaning service by expert technicians.', price: 499, duration_minutes: 105 },
          { id: 1061, category_id: 12, name: 'Door Alignment', description: 'Professional door alignment service by expert technicians.', price: 299, duration_minutes: 45 },
          { id: 1062, category_id: 12, name: 'Door Handle Repair', description: 'Professional door handle repair service by expert technicians.', price: 349, duration_minutes: 60 },
          { id: 1063, category_id: 12, name: 'Window Repair', description: 'Professional window repair service by expert technicians.', price: 399, duration_minutes: 75 },
          { id: 1064, category_id: 12, name: 'Glass Replacement', description: 'Professional glass replacement service by expert technicians.', price: 449, duration_minutes: 90 },
          { id: 1065, category_id: 12, name: 'Mosquito Net Installation', description: 'Professional mosquito net installation service by expert technicians.', price: 499, duration_minutes: 105 }
        ];