"""Create customer addresses

Revision ID: 0809cdbcf61b
Revises: 6b1f4f9a2e31
Create Date: 2026-07-23 23:08:47.738627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0809cdbcf61b'
down_revision: Union[str, Sequence[str], None] = '6b1f4f9a2e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'customer_addresses' in tables:
        op.drop_table('customer_addresses')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('house_no', sa.String(length=100), nullable=False),
    sa.Column('building', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('area', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_addresses_customer_id'), 'customer_addresses', ['customer_id'], unique=False)
    op.create_index('ix_customer_addresses_customer_id_default', 'customer_addresses', ['customer_id', 'is_default'], unique=False)
    op.create_index(op.f('ix_customer_addresses_id'), 'customer_addresses', ['id'], unique=False)
    if 'booking_timelines' in tables:
        try:
            op.drop_index(op.f('ix_booking_timelines_id'), table_name='booking_timelines')
        except Exception:
            pass
        op.drop_table('booking_timelines')
    op.add_column('bookings', sa.Column('booking_number', sa.String(length=100), nullable=False))
    op.add_column('bookings', sa.Column('address_id', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('booking_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('bookings', sa.Column('preferred_time', sa.String(length=50), nullable=True))
    op.add_column('bookings', sa.Column('estimated_price', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('final_price', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus', native_enum=False), nullable=False))
    op.add_column('bookings', sa.Column('customer_note', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('admin_note', sa.Text(), nullable=True))
    op.alter_column('bookings', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_bookings_booking_number'), 'bookings', ['booking_number'], unique=True)
    op.drop_constraint(op.f('bookings_service_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_technician_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_customer_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'customer_addresses', ['address_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'bookings', 'users', ['technician_id'], ['id'], ondelete='SET NULL')
    op.drop_column('bookings', 'notes')
    op.drop_column('bookings', 'scheduled_at')
    op.drop_column('bookings', 'address')
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('services_category_id_fkey'), 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key(op.f('services_category_id_fkey'), 'services', 'categories', ['category_id'], ['id'])
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('bookings', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_customer_id_fkey'), 'bookings', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('bookings_technician_id_fkey'), 'bookings', 'technicians', ['technician_id'], ['id'])
    op.create_foreign_key(op.f('bookings_service_id_fkey'), 'bookings', 'services', ['service_id'], ['id'])
    op.drop_index(op.f('ix_bookings_booking_number'), table_name='bookings')
    op.alter_column('bookings', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('bookings', 'admin_note')
    op.drop_column('bookings', 'customer_note')
    op.drop_column('bookings', 'payment_status')
    op.drop_column('bookings', 'final_price')
    op.drop_column('bookings', 'estimated_price')
    op.drop_column('bookings', 'preferred_time')
    op.drop_column('bookings', 'booking_date')
    op.drop_column('bookings', 'address_id')
    op.drop_column('bookings', 'booking_number')
    op.create_table('booking_timelines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('booking_timelines_booking_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_timelines_pkey'))
    )
    op.create_index(op.f('ix_booking_timelines_id'), 'booking_timelines', ['id'], unique=False)
    op.drop_index(op.f('ix_customer_addresses_id'), table_name='customer_addresses')
    op.drop_index('ix_customer_addresses_customer_id_default', table_name='customer_addresses')
    op.drop_index(op.f('ix_customer_addresses_customer_id'), table_name='customer_addresses')
    op.drop_table('customer_addresses')
    # ### end Alembic commands ###
