"""Add technician fields

Revision ID: 55bf0050f96f
Revises: 46e5f4b6aca1
Create Date: 2026-07-23 19:17:17.224660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55bf0050f96f'
down_revision: Union[str, Sequence[str], None] = '46e5f4b6aca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technicians', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('technicians', sa.Column('languages', sa.JSON(), nullable=True))
    op.add_column('technicians', sa.Column('working_hours', sa.String(length=255), nullable=True))
    op.add_column('technicians', sa.Column('is_online', sa.Boolean(), nullable=False))
    op.add_column('technicians', sa.Column('service_radius_km', sa.Float(), nullable=True))
    op.add_column('technicians', sa.Column('profile_image', sa.String(length=500), nullable=True))
    op.add_column('technicians', sa.Column('government_id_image', sa.String(length=500), nullable=True))
    op.add_column('technicians', sa.Column('reviews_count', sa.Integer(), nullable=False))
    op.add_column('technicians', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technicians', 'updated_at')
    op.drop_column('technicians', 'reviews_count')
    op.drop_column('technicians', 'government_id_image')
    op.drop_column('technicians', 'profile_image')
    op.drop_column('technicians', 'service_radius_km')
    op.drop_column('technicians', 'is_online')
    op.drop_column('technicians', 'working_hours')
    op.drop_column('technicians', 'languages')
    op.drop_column('technicians', 'skills')
    # ### end Alembic commands ###
