"""Add dual verification fields to qr_verifications

Revision ID: fcc910155e51
Revises: f91a842ee637
Create Date: 2026-09-04 15:12:35.744637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc910155e51'
down_revision: Union[str, Sequence[str], None] = 'f91a842ee637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_verifications', sa.Column('pin_attempt_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('qr_verifications', sa.Column('customer_pin_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('qr_verifications', sa.Column('technician_qr_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('qr_verifications', sa.Column('customer_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('qr_verifications', sa.Column('technician_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('qr_verifications', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('qr_verifications', sa.Column('verification_status', sa.String(length=50), nullable=False, server_default='pending'))
    op.alter_column('qr_verifications', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('qr_verifications', 'expires_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('qr_verifications', 'verification_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    user_cols = [c['name'] for c in inspector.get_columns('users')]
    user_indices = [idx['name'] for idx in inspector.get_indexes('users')]

    if 'ix_users_username' in user_indices:
        op.drop_index('ix_users_username', table_name='users')
    if 'username' in user_cols:
        op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=255), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.alter_column('qr_verifications', 'verification_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('qr_verifications', 'expires_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('qr_verifications', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('qr_verifications', 'verification_status')
    op.drop_column('qr_verifications', 'verified_at')
    op.drop_column('qr_verifications', 'technician_confirmed_at')
    op.drop_column('qr_verifications', 'customer_confirmed_at')
    op.drop_column('qr_verifications', 'technician_qr_verified_at')
    op.drop_column('qr_verifications', 'customer_pin_verified_at')
    op.drop_column('qr_verifications', 'pin_attempt_count')
    # ### end Alembic commands ###
